### ISSUE TITLE
Install error on negspacy (pip install)

### ISSUE THREAD

**Issue by GB-TA** [jenojp/negspacy#1]
**Describe the bug**
Getting the below error with pip install negspacy command in Anacondo Prompt.

**To Reproduce**
Run Anaconda Prompt as Administrator
type - pip install negspacy and enter
**Expected behavior**
negspacy package gets install and should be present in C:\ProgramData\Anaconda3\Lib\site-packages

**Screenshots**
(base) C:\WINDOWS\system32>pip install C:\negspacy-0.1.0a0.tar.gz
Processing c:\negspacy-0.1.0a0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\programdata\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-req-build-4b2hz8em\\setup.py'"'"'; __file__='"'"'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-req-build-4b2hz8em\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\xxAppData\Local\Temp\pip-req-build-4b2hz8em\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xx\AppData\Local\Temp\pip-req-build-4b2hz8em\setup.py", line 10, in <module>
        long_description=open("README.md").read(),
      File "c:\programdata\anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 274: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by jenojp** [comment]
Hi, thank you for raising this issue. Please try installing again and let me know if you continue to get the issue.
```
pip install negspacy --upgrade
```

I think I fixed the windows decoding issue.

**Comment by jenojp** [comment]
Replicated the issue on azure and had no issue when installing the new version. Let me know if you're still having the problem. Thanks!

**Comment by GB-TA** [comment]
Thank Jeno for fixing the issue with negspacy install. I was able to install negspacy and import the packages.

Ran:
nlp = spacy.load("en_core_web_sm")
negex = Negex(nlp)
nlp.add_pipe(negex, last=True)
Im trying to see how negation works with different scenarios:
doc = nlp(" Client is not on the Terrorists watchlist.")
Result:
Terrorists True
doc = nlp(" Client is not on the Terrorists Watch list.")
Result:
Terrorists True
doc = nlp(" Client is not on the Terrorist Watchlist.")
Result : NULL
doc = nlp(" Client is not on the Terrorists watch list.")
Result : NULL
doc = nlp(" Client is not on the terrorists watch list.")
Result : NULL

doc = nlp("Client is not affiliated to Soverign citizen.")
Result : Soverign True
doc = nlp("Client is not affiliated to soverign citizen.")
Result : NULL

Could you please check and explain why the negation detection is failing with some texts which is very close to how the successful ones are written? Is there a NER dictionary that is being being used behind the seen to identify Org entities?
Please let me know if there is  a way to fix this

**Comment by jenojp** [comment]
Oh good! I'm glad that issue is resolved.

Yes - You're using the built in spaCy NER in the backend. If you have a specific dictionary of entities you'd like to process, I would suggest using the [EntityRuler](https://spacy.io/usage/rule-based-matching#entityruler) in spaCy. 

This way you could make your own new entities or add patterns to existing ones.

**Comment by GB-TA** [comment]
Thank you!  Looking forward to enhancements on this. Great work with this package!
