### ISSUE TITLE
negspacy pairing example

### ISSUE THREAD

**Issue by aficionadoai** [jenojp/negspacy#13]
Thank you for creating negspacy! This is extremely helpful. I was wondering you can provide more detail on `Consider pairing with scispacy to find UMLS concepts in text and process negations.` ?

I searched Google and was not able to find any examples.  How do you pair with othet spacy elements.

**Comment by jenojp** [comment]
No problem! So I'm not sure how familiar you are with the inner workings of spacy but it has a really nicely designed way of processing text as a [pipeline](https://spacy.io/usage/processing-pipelines). If you're newer to spacy, I 100% recommend the [course](https://course.spacy.io) by @ines as it does a wonderful job of explaining this. So in this case, negspacy is a custom pipeline component that adds an extension to spans. (Entities in spacy are treated as spans). 

What I meant in the README was that you can use the [scispacy](https://github.com/allenai/scispacy) language model and their [UMLS entitylinker](https://github.com/allenai/scispacy#umlsentitylinker-alpha-feature) in conjunction with negspacy  to find specific UMLS concepts that are or are not negated.

For example:

```python
import spacy
import scispacy
from negspacy.negation import Negex
from scispacy.umls_linking import UmlsEntityLinker

nlp = spacy.load("en_core_sci_sm")
linker = UmlsEntityLinker()
#this can take a while the first time
nlp.add_pipe(linker)

negex = Negex(nlp, chunk_prefix = ["no"])
nlp.add_pipe(negex, last=True)
```

Then if you process a doc, you could access two new custom extensions `._.negex` and `._.umls_ents`

```python
doc = nlp("Patient denies cardiovascular disease but has headaches. No history of smoking. Alcoholism unlikely. Smoking not ruled out.")

for e in doc.ents:
    print(e.text, e._.negex, e._.umls_ents)

```


There are many different spacy pipeline components [here](https://spacy.io/universe/category/pipeline)

**Comment by aficionadoai** [comment]
Thank you very much @jenojp

**Comment by kaushikacharya** [comment]
> ```python
> from scispacy.umls_linking import UmlsEntityLinker
> ```

As per the current release of scispacy, it should be
```python
from scispacy.linking import EntityLinker
```

And 
>```python
>linker = UmlsEntityLinker()
>```
should be 
```python
linker = EntityLinker(resolve_abbreviations=True, name="umls")
```
