### ISSUE TITLE
Is it possible to apply Negspacy over token?

### ISSUE THREAD

**Issue by Raghu17s** [jenojp/negspacy#18]
Hi,

How can I apply negations on the token? is it possible?

I tried following but it ended up in error.
`for token in doc:

    print(token.text, token._.negex)
`
The error is
`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1331-cc0d2437d96e> in <module>
      1 for token in doc:
----> 2     print(token.text, token._.negex)

~/anaconda3/envs/python3/lib/python3.6/site-packages/spacy/tokens/underscore.py in __getattr__(self, name)
     33     def __getattr__(self, name):
     34         if name not in self._extensions:
---> 35             raise AttributeError(Errors.E046.format(name=name))
     36         default, method, getter, setter = self._extensions[name]
     37         if getter is not None:

AttributeError: [E046] Can't retrieve unregistered extension attribute 'negex'. Did you forget to call the `set_extension` method?
`

**Comment by jenojp** [comment]
Unfortunately, no as it is an extension for "spans" only.
