### ISSUE TITLE
Error while processing the example

### ISSUE THREAD

**Issue by prabhatM** [jenojp/negspacy#22]
Hi **I am getting the following error while trying to process the example with UmlsEntityLinker()** :+1: 

File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
[Sun Sep 20 16:41:24.954031 2020] [wsgi:error] [pid 458:tid 140686318831360] [remote 122.176.234.216:63073]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[Sun Sep 20 16:41:24.954035 2020] [wsgi:error] [pid 458:tid 140686318831360] [remote 122.176.234.216:63073]   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
[Sun Sep 20 16:41:24.954041 2020] [wsgi:error] [pid 458:tid 140686318831360] [remote 122.176.234.216:63073]     raise JSONDecodeError("Expecting value", s, err.value) from None
[Sun Sep 20 16:41:24.954045 2020] [wsgi:error] [pid 458:tid 140686318831360] [remote 122.176.234.216:63073] 

**json.decoder.JSONDecodeError: Expecting value: line 1 column 219152385 (char 219152384)**

I am using Python 3.8.2

Please help.

Regards

Prabhat

**Comment by jenojp** [comment]
Could you share your code so I could reproduce?

**Comment by jenojp** [comment]
Without more information, the error trace appears to be an issue with a JSON file that you're decoding. This would likely be with python JSON library and unrelated to negspacy. I'm going to close this issue.
