### ISSUE TITLE
When running example it returns "Steve Jobs False"

### ISSUE THREAD

**Issue by ThomasBurgess2000** [jenojp/negspacy#30]
**Describe the bug**
When I run this example code: 

```
import spacy
from negspacy.negation import Negex

nlp = spacy.load("en_core_web_sm")
negex = Negex(nlp, ent_types=["PERSON','ORG"])
nlp.add_pipe(negex, last=True)

doc = nlp("She does not like Steve Jobs but likes Apple products.")
for e in doc.ents:
    print(e.text, e._.negex)
```

It outputs:
Steve Jobs False
Apple False

**Expected behavior**
Steve Jobs True

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by jenojp** [comment]
Hi @ThomasBurgess2000 - look at the mixing of single and double quotes in line 5 of your example. I think that's what's causing the issue.

**Comment by ThomasBurgess2000** [comment]
That is the issue, thank you! However, I copied the code from here so you might want to update it: https://spacy.io/universe/project/negspacy

**Comment by jenojp** [comment]
Oh whoops - thanks for spotting that, I just double checked the readme but didn't think of there!

**Comment by jenojp** [comment]
fixed on spacy webpage https://github.com/explosion/spaCy/pull/6578
