### ISSUE TITLE
Error with the termset

### ISSUE THREAD

**Issue by Aminolroaya** [jenojp/negspacy#32]
Hi,

With negspacy 1.0.0 and spacy 3.0.1, I get the error for using termsets:

'negex -> neg_tersmset   extra fields not permitted'
```
    nlp = spacy.load("en_core_web_sm")
    ts = termset("en")
    nlp.add_pipe(
        "negex",
        config={
            "neg_tersmset": ts.get_patterns()
        }
    ) 

```
Can you help?

**Comment by jenojp** [comment]
Looks like a typo in "neg_termset". Give that a shot!

**Comment by Aminolroaya** [comment]
Thanks :D
