### ISSUE TITLE
extract patterns out the negated entities

### ISSUE THREAD

**Issue by hollywzw** [jenojp/negspacy#36]
Hi, how do we extract the patterns of the negations identified? Is there any standard methods of negex we can use?

Like if I want to know which negation pattern below was identified for the negated entity.

NegEx Patterns
psuedo_negations - phrases that are false triggers, ambiguous negations, or double negatives
preceding_negations - negation phrases that precede an entity
following_negations - negation phrases that follow an entity
termination - phrases that cut a sentence in parts, for purposes of negation detection (.e.g., "but")

**Comment by jenojp** [comment]
Hi, currently there is not a standard method for doing this. Essentially for each named entity, negspacy checks to see if a negation pattern either precedes or follows it, provided that it is not a pseudo negation and is within a sentence boundary. If any are found, the named entity gets a negex extension of `True` and it moves onto the next. The various patterns aren't saved or evaluated completely.
