### ISSUE TITLE
spacy-2.2.3 

### ISSUE THREAD

**Issue by mahbub029** [jenojp/negspacy#9]
**Describe the bug**
uninstalls the latest spacy 2.2.3 and reinstalls an older version spacy 2.1.8.
**To Reproduce**
pip install negspacy
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS Mojave]

**Additional context**

**Comment by jenojp** [comment]
Hey @mahbub029 , on it!

**Comment by jenojp** [comment]
Hey just pushed a new release. Give `pip install negspacy --upgrade` a shot.

**Comment by mahbub029** [comment]
Perfect! Thanks a lot. Appreciate quick help.
